<?php
/**
 * DistrictAdminsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Clever
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Data API
 *
 * Serves the Clever Data API
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Clever\Test\Api;

use \Clever\Configuration;
use \Clever\ApiException;
use \Clever\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DistrictAdminsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Clever
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DistrictAdminsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getDistrictAdmin
     *
     * .
     *
     */
    public function testGetDistrictAdmin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDistrictAdmins
     *
     * .
     *
     */
    public function testGetDistrictAdmins()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDistrictForDistrictAdmin
     *
     * .
     *
     */
    public function testGetDistrictForDistrictAdmin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
